api & client: set config value via request body. Closes #3283 (#4313)
* flask api: add return statement on config option deletion

Fixes following error on config deletion:
TypeError: The view function did not return a valid response.
The function either returned None or ended without a return statement.

* api & client: set config value via request body. Closes #3283

Before this patch, the config values where passed to the api endpoint
via the url. This resulted in some undesired behaviors. For example, as
stated by the linked issue, the value '.' was interpreted by the web
server and never passed to rucio logic. Other edge cases where also
possible. For example setting the following values: '../../', 'a?x=y'
would not work correctly.

Introduce a new POST /config endpoint which accepts json of format
{"section": {"option": "value"}}.
To maintain compatibility with existing clients, we support the old
endpoint for the time being.

Maintain compatibility in the ConfigClient class to use it in tests
and check non-regression on the deprecated endpoint.