Core & Internals: rework sql bindparams passing in filter_thread_work
Got the following exception in daemons during the 1.26.0rc1 release:
TypeError: text() got an unexpected keyword argument 'bindparams'

Which corresponds to the documentation:
https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.text

I don't know how it worked before, maybe some deprecated kwarg which
was removed in the latest sqlalchemy release.