Testing: Ruff, Ignore UP037
Ruff 0.4.5 changes the logic used to detect UP037,
mainly via this PR: https://github.com/astral-sh/ruff/pull/11485.

I am seeing some possible false positive due to this, e.g.:

> Error: lib/rucio/core/authentication.py:571:27: UP037 Remove quotes from type annotation

where it asks to remove quotes from  a type
that's only imported in a type-checking block.

This is a very new Ruff version so it's best to check back at a later
point to see if this is a common issue for other repositories too.